name: Deploy to AWS Windows Instance

on:
  push:
    branches:
      - master

env:
  AWS_REGION: ap-south-1

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/setup-aws-cli@v1
      with:
        aws-access-key-id: AKIAWNZAYHOKNOWUJKNG
        aws-secret-access-key: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
        aws-region: ${{ env.AWS_REGION }}

    - name: Deploy code to AWS Windows Instance
      uses: aws-actions/amazon-ec2-instance-control@v1
      with:
        command: copy
        instance-ids:i-0072ec5be79770c7a
        source: .
        destination: C:\inetpub\wwwroot
